"""added table for refresh tokens

Revision ID: 5d65b2bf71cc
Revises: fd86c41fc531
Create Date: 2026-03-11 12:18:24.351466

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d65b2bf71cc'
down_revision: Union[str, Sequence[str], None] = 'fd86c41fc531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
