"""renaming task object column

Revision ID: e99cba66e2d4
Revises: fb4152324563
Create Date: 2026-03-12 18:54:30.212889

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e99cba66e2d4'
down_revision: Union[str, Sequence[str], None] = 'fb4152324563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='taskstatus'), nullable=False))
    op.drop_column('task', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status_id', postgresql.ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='taskstatus'), autoincrement=False, nullable=False))
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
