"""removing user_type from user model

Revision ID: fb4152324563
Revises: 4a7caeebb05e
Create Date: 2026-03-12 10:07:33.318137

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb4152324563'
down_revision: Union[str, Sequence[str], None] = '4a7caeebb05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', postgresql.ENUM('ADMIN', 'MEMBER', 'OWNER', name='usertype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
